src/logger.c: bugfix self-comparison always evaluates to true
When compiling with gcc 8.4.0 with -Werror, the following error is
thrown:

src/logger.c:72:40: error: self-comparison always evaluates to true [-Werror=tautological-compare]
  while (*p != '\0' && *q != '\0' && *p == *p) {
                                        ^~
cc1: some warnings being treated as errors

It is assumed that *p needs to be compared with *q